### ISSUE TITLE
Weird Outpaint Issues

### ISSUE THREAD

**Issue by ClashSAN** [v8hid/infinite-zoom-automatic1111-webui#1]
hi @v8hid,
thank you for working on this, the ui looks great!

I'm not sure if you were previously aware some others were also working on infinite zoom:
https://github.com/coolzilj/infinite-zoom
https://github.com/juanigsrz/sd-fractal-zoom

And there seems to be **a problem with webui's outpainting itself**, noted - https://github.com/coolzilj/infinite-zoom#known-issues

>You may notice a distinct frame or seam around the image, although it's less noticeable in the original diffusers version.

There are some experts in webui discussions posts who may know the reason, I don't.
Maybe we could see what @coolzilj thinks about this issue, and which extension is better to be maintained

**Comment by v8hid** [comment]
Hi @ClashSAN,

Thank you so much for your help! I wasn't aware of the other extensions you mentioned, but I checked them out and they seem to be useful.

I've tested my extension in many ways and it appears to be working fine. However, I did encounter a frame problem at first that I was able to trace back to the `mask_blur` option. It seems that `mask_blur` alters the initial image slightly and removes pixels around the image, which causes a conflict when trying to interpolate between the changed image and the original one. Nevertheless, I found a workaround by setting `mask_blur = 0`. additionally using inpainting models, and a sensible prompt makes the result much more consistent. I've provided some examples in the Example section of the Readme for you to check out.

I'm also happy to report that I've received positive feedback from a few users who followed the solution I suggested. They seem to be happy with the results.

Looking ahead, I have some plans to add new functionalities and features that will require a separate tab. If @coolzilj is interested in contributing, I would be more than happy to add them as a collaborator so that we can work on this together. Thank you again for your help and support!

**Comment by coolzilj** [comment]
> hi @v8hid, thank you for working on this, the ui looks great!
> 
> I'm not sure if you were previously aware some others were also working on infinite zoom: https://github.com/coolzilj/infinite-zoom https://github.com/juanigsrz/sd-fractal-zoom
> 
> And there seems to be **a problem with webui's outpainting itself**, noted - https://github.com/coolzilj/infinite-zoom#known-issues
> 
> > You may notice a distinct frame or seam around the image, although it's less noticeable in the original diffusers version.
> 
> There are some experts in webui discussions posts who may know the reason, I don't. Maybe we could see what @coolzilj thinks about this issue, and which extension is better to be maintained

I don't have time to investigate the cause of this issue, so if @v8hid fix it, you should add it to the index.
