### ISSUE TITLE
Speed of zoom-in or out

### ISSUE THREAD

**Issue by h0x91b** [v8hid/infinite-zoom-automatic1111-webui#4]
Hi, thanks for extension!

Is it possible to add another slider that controls the zoom speed?

I want to make a video with this effect, but at a much slower speed...

**Comment by v8hid** [comment]
Hi @h0x91b,
Great job on your contribution! Thank you for taking the time to add the Zoom speed slider to the extenstion. I appreciate your efforts and the value you bring to this project.

After conducting a quick review, I will merge your pull request. Additionally, if you are interested in making more contributions, we have a list of future features that we would love to implement. I would be happy to share that list with you so that you can add any features you think would be beneficial. Let me know if you are interested, and thank you again.

**Comment by h0x91b** [comment]
Can you share the list, maybe I can help there?

**Comment by v8hid** [comment]
@h0x91b  #5 merged
I have some ideas for organizing the future feature list. I will work on organizing it and share it with you as soon as possible. If you are interested in discussing these features further, we can communicate more directly on our Discord server. Once again, thank you for your contribution, and I look forward to collaborating with you in the future.

**Comment by v8hid** [comment]
Hi again @h0x91b, 
I invited you to a GitHub project I made for this extension, I listed some of the features over there.

**Comment by h0x91b** [comment]
will try do to some task from list today

**Comment by v8hid** [comment]
@h0x91b Did you find anything you want to work on? 
Let me know if you need any help.
