### ISSUE TITLE
360 Panorama

### ISSUE THREAD

**Issue by Tobe2d** [v8hid/infinite-zoom-automatic1111-webui#72]
Any guide on how to generate 360 Panorama?

**Comment by GeorgLegato** [comment]
If creating non-zoomed-movies, just use either
* prompt "360 full panorama of bikini bottom" 
* A 360-Lora
* Existing 360panoramas and use these as depth-map template with controlnet

in infnite-zoom try the prompt, but only in first image or in the init -image and zoom in.

To view the 360-movie you need t install my Panorama-Viewer-Extension. It adds an additional window next to INfZoom-Player and/or provide a dedicated Tab which plays 360-movies (Firefox cannot open any videos due to a bug)

**Comment by GeorgLegato** [comment]
https://github.com/GeorgLegato/sd-webui-panorama-viewer
